name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          # Create API Token from `Edit Cloudflare Workers` template: https://dash.cloudflare.com/profile/api-tokens
          apiToken: ${{ secrets.CF_API_TOKEN }}
