name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          # Create API Token from `Edit Cloudflare Workers` template: https://dash.cloudflare.com/profile/api-tokens
          apiToken: ${{ secrets.CF_API_TOKEN_2 }}
